### ISSUE TITLE
Correct recipes path question

### ISSUE THREAD

**Issue by tigattack** [ferdium/ferdium-server#121]
In the Docker image, should recipes definitely be at `/app/build/recipes`, per the docs?

The docs were updated to reference this path in #97, but the entrypoint script still uses `/app/recipes`, so I'm not sure if the docs are wrong or if the entrypoint script is wrong.

I have a patch ready for the entrypoint but thought I'd ask the question first.

**Comment by haakobja** [comment]
I've got the same question. I've previously mounted my recipes-volume to `/app/build/recipes`, but after checking `entrypoint.sh` I changed the mount path to `/app/recipes`. I haven't figured out which is correct, yet. But it's most likely `/app/recipes`

**Comment by jdmallen** [comment]
Ran into this myself and did some heavy debugging with the help of local agents. Below is the summary.

Neither documented mount path works, because the entrypoint and the controller use different directories for the recipes. I hit this on 2.0.13: `GET /v1/recipes` returns 500.
```
{"message":"/app/build/recipes/all.json: ENOENT: no such file or directory,
open '/app/build/recipes/all.json'"}
```
Server log (JSON formatting mine):
```
✅ Successfully packaged and added 438 recipes (0 unsuccessful recipes) in 26.859 seconds
...
{
    "level": 50,
    "time": 1788283014144,
    "pid": 1938,
    "hostname": "a02650bcd8b2",
    "name": "ferdium-server",
    "err": {
        "type": "Error",
        "message": "/app/build/recipes/all.json: ENOENT: no such file or directory, open '/app/build/recipes/all.json'",
        "stack": "Error: /app/build/recipes/all.json: ENOENT: no such file or directory, open '/app/build/recipes/all.json'\n    at Object.openSync (node:fs:561:18)\n    at Object.readFileSync (node:fs:445:35)\n    at Object.readFileSync (/app/node_modules/.pnpm/jsonfile@6.2.0/node_modules/jsonfile/index.js:50:22)\n    at RecipesController.list (/app/app/Controllers/Http/RecipeController.ts:53:32)\n    at Injector.callAsync (/app/node_modules/.pnpm/@adonisjs+fold@8.2.0/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)",
        "errno": -2,
        "code": "ENOENT",
        "syscall": "open",
        "path": "/app/build/recipes/all.json",
        "status": 500
    },
    "msg": "/app/build/recipes/all.json: ENOENT: no such file or directory, open '/app/build/recipes/all.json'"
}
```
The entrypoint reports successfully packaging 438 recipes. The controller then fails to find them because the two components use different directories.

### Root cause

`Application.appRoot` resolves to `/app/build`, not `/app`. The ENOENT path above shows it: `RecipeController` does `path.join(Application.appRoot, 'recipes', 'all.json')`, which gives `/app/build/recipes/all.json`.

`docker/entrypoint.sh` runs with `WORKDIR /app` and clones the recipes repo into `/app/recipes`, then runs `pnpm i` and `pnpm package` there.

| Component | Path used |
|---|---|
| `entrypoint.sh` (clones, builds, writes `all.json` + `archives/`) | `/app/recipes` |
| `RecipeController` (reads `all.json`, writes custom uploads to `archives/`) | `/app/build/recipes` |

Both documented mount choices are self-consistent, but each fails:

- Mount at `/app/recipes` (what the root `README.md` and the entrypoint's inline comment suggest): the entrypoint's work is persisted, but the app reads `/app/build/recipes`, which never exists, so `GET /v1/recipes` returns 500.
- Mount at `/app/build/recipes` (what `docker/README.md` and `docker/docker-compose.yml` suggest): Docker creates the directory, but the entrypoint never writes to it, so it stays empty and the controller can't find `all.json`.

This also explains #97: it wasn't a bad merge. It moved the docs to the path the app actually reads; it just didn't move the entrypoint to match.

Neither directory ships in the image. Verified with no volumes mounted:
```
$ docker run --rm --entrypoint sh ferdium/ferdium-server:latest -c 'ls -d /app/build /app/recipes /app/build/recipes'
/app/build
ls: /app/recipes: No such file or directory
ls: /app/build/recipes: No such file or directory
```
`/app/build` already exists (it holds the compiled output: `server.js`, `ace`, `config`, etc.); `/app/recipes` doesn't exist until the entrypoint creates it at runtime.

### Verification

A symlink between the two directories fixes it, with no other changes:
```
$ docker exec ferdium sh -c 'ln -sfn /app/recipes /app/build/recipes'
$ curl -s -o /dev/null -w '%{http_code}' https://<server>/v1/recipes
200          # 438 recipes returned, previously 500
```

### Workaround

Mount the same volume at both paths:
```yaml
volumes:
  - ferdium_recipes:/app/recipes
  - ferdium_recipes:/app/build/recipes
```
This covers custom recipes too: `RecipeController.create` writes to `Application.appRoot + '/recipes/archives/<id>.tar.gz'`, i.e. `/app/build/recipes/archives`, which is on the same volume.

### Suggested fix

Make the entrypoint and the controller agree on the directory, and the docs agree with both. Concretely: have `entrypoint.sh` clone and package into the directory the app resolves from (or set `appRoot` so the controller sees `/app/recipes`), and update `docker/README.md`, `docker/docker-compose.yml`, and the root `README.md` to match.

One more problem with the current state, for anyone following `docker/README.md`: the volume is bound to a directory that nothing writes to, so `/app/recipes` lives in the container's writable layer. Two consequences:

- Every container replacement re-clones ferdium-recipes and re-runs `pnpm i` and `pnpm package` before the server listens.
- Custom recipes are discarded on image updates, while their rows remain in the `recipes` table, so the database and the filesystem diverge with no error indicating it.

### Environment

- Image: `ferdium/ferdium-server:latest` (2.0.13, published 2026-03-28)
- Architectures: linux/arm64, linux/amd64
- Docker on Raspberry Pi OS 13 and on my desktop
- SQLite, `DATA_DIR=/data`

**Comment by haakobja** [comment]
Does the NODE_ENV have any effect? I see that it in some of the examples is set to Development and to Production in others. I've set up my ferdium server with `NODE_ENV=Production` and mounted the recipes volume to `/app/recipes`
