### ISSUE TITLE
docker-compose deployment throws error Cannot find module 'image-size'

### ISSUE THREAD

**Issue by typoworx-de** [ferdium/ferdium-server#63]
I'm trying to deploy own private ferdium-server.

The docker logs are throwing some module-errors:
```
node:internal/modules/cjs/loader:988

  throw err;
  ^
Error: Cannot find module 'image-size'
Require stack:
- /app/recipes/scripts/package.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/app/recipes/scripts/package.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/recipes/scripts/package.js' ]
}
 ELIFECYCLE  Command failed with exit code 1.
**** App key is . You can modify `/data/FERDIUM_APP_KEY.txt` to update the app key ****
Nothing to migrate
info: serving app on http://0.0.0.0:3333
-------------------------------------
       ______              ___
      / ____/__  _________/ (_)_  ______ ___
     / /_  / _ \/ ___/ __  / / / / / __ `__ \
    / __/ /  __/ /  / /_/ / / /_/ / / / / / /
   /_/    \___/_/   \__,_/_/\__,_/_/ /_/ /_/
      _____
     / ___/___  ______   _____  _____
     \__ \/ _ \/ ___/ | / / _ \/ ___/
    ___/ /  __/ /   | |/ /  __/ /
   /____/\___/_/    |___/\___/_/
Brought to you by ferdium.org
**** Updating recipes ****
Saved working directory and index state WIP on main: 9da964e Upgrade 'pnpm' to '7.26.1'
Already up to date.
Already up to date.
On branch main
Your branch is up to date with 'origin/main'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.pnpm-store/
nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} (d67631be69f11b88fdf1dc32145bfda110d6ae01)
npm WARN using --force Recommended protections disabled.
changed 1 package, and audited 2 packages in 520ms
1 package is looking for funding
  run `npm fund` for details
found 0 vulnerabilities
Scope: all 284 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
devDependencies: skipped because NODE_ENV is set to production
. prepare$ pnpm dlx husky install
. prepare: .pnpm-store/v3/tmp/dlx-74                | Progress: resolved 1, reused 0, downloaded 0, added 0
. prepare: .pnpm-store/v3/tmp/dlx-74                |   +1 +
. prepare: husky - Git hooks installed
. prepare: .pnpm-store/v3/tmp/dlx-74                | Progress: resolved 1, reused 1, downloaded 0, added 1, done
. prepare: Done

Done in 1.9s
> ferdium-recipes@1.0.1 package /app/recipes
> node scripts/package.js
node:internal/modules/cjs/loader:988

  throw err;
  ^
Error: Cannot find module 'image-size'
Require stack:
- /app/recipes/scripts/package.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/app/recipes/scripts/package.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/recipes/scripts/package.js' ]
}
 ELIFECYCLE  Command failed with exit code 1.
**** App key is . You can modify `/data/FERDIUM_APP_KEY.txt` to update the app key ****
Nothing to migrate
info: serving app on http://0.0.0.0:3333
```

This is my (slightly) modified docker-compose.yml:
```
version: "2"
services:
  ferdium-server:
    image: ferdium/ferdium-server:latest
    container_name: ferdium-server
    env_file: .env.local
    environment:
      - DATA_DIR=/data
      - PUID=1000
      - PGID=1000
    volumes:
      - database.ferdium:/data
      - recipes.ferdium:/app/recipes
    ports:
      - 3333:3333
    restart: unless-stopped
volumes:
  database.ferdium:
  recipes.ferdium:
```

and my .env.local environment file (with some masked stuff):
```
# !!! Development-ENV is required for first-time setup !!!
NODE_ENV=development
#NODE_ENV=production

APP_URL=ferdium.typoworx.com
DB_CONNECTION=sqlite
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER=root
DB_PASSWORD=*********
DB_DATABASE=ferdium
DB_SSL=false
MAIL_CONNECTION=smtp
SMTP_HOST=mail.my-own-hots.com
SMTP_PORT=587
MAIL_SSL=true
MAIL_USERNAME=relay@mail.my-own-hots.com
MAIL_PASSWORD=**********
MAIL_SENDER=no-reply@ferdium.my-own-hots.com
IS_CREATION_ENABLED=true
IS_DASHBOARD_ENABLED=true
IS_REGISTRATION_ENABLED=true
```

Whats wrong there?! Will I need something else than docker-compose.yml which should use the latest image?

**Comment by typoworx-de** [comment]
Somehow... got it working after figuring out I had to manually generate & store APP_KEY.
