### ISSUE TITLE
Database migration error

### ISSUE THREAD

**Issue by kromonos** [ferdium/ferdium-server#84]
```
-- Starting database migration from AdonisJS v4 to v5 --
Updating value from 'database/migrations/database/migrations/database/migrations/1503250034279_user' to 'database/migrations/database/migrations/database/migrations/database/migrations/1503250034279_user'
Updating value from 'database/migrations/database/migrations/database/migrations/1503250034280_token' to 'database/migrations/database/migrations/database/migrations/database/migrations/1503250034280_token'
Updating value from 'database/migrations/database/migrations/database/migrations/1566385379883_service_schema' to 'database/migrations/database/migrations/database/migrations/database/migrations/1566385379883_service_schema'
Updating value from 'database/migrations/database/migrations/database/migrations/1566554231482_recipe_schema' to 'database/migrations/database/migrations/database/migrations/database/migrations/1566554231482_recipe_schema'
Updating value from 'database/migrations/database/migrations/database/migrations/1566554359294_workspace_schema' to 'database/migrations/database/migrations/database/migrations/database/migrations/1566554359294_workspace_schema'
Updating value from 'database/migrations/database/migrations/database/migrations/1612629845398_users_update_schema' to 'database/migrations/database/migrations/database/migrations/database/migrations/1612629845398_users_update_schema'
❯ error database/migrations/1503250034279_user
❯ migrating database/migrations/1696110557648_jwt_tokens
[ error ]  create table "users" ("id" serial primary key, "username" varchar(80) not null, "email" varchar(254) not null, "password" varchar(60) not null, "settings" json, "created_at" timestamptz, "updated_at" timestamptz) - relation "users" already exists
    at Parser.parseErrorMessage (/app/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Socket.Readable.push (node:internal/streams/readable:245:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
``` 

Using Ferdium-Server via Docker with tag `latest`

**Comment by SpecialAro** [comment]
Hello 👋 which tag were you using before updating?

**Comment by SpecialAro** [comment]
Can you manually access the database and delete the `database/migrations/database/migrations/database/migrations/database/migrations/` on all rows on the adonis migration table ? That seems to be the issue.
 It should be just `1503250034279_user` and the script would add `database/migrations/` by itself

If this is too technical and you don't mind DM me (on discord perhaps) the sqlite database I can fix it for you!

**Comment by SpecialAro** [comment]
> hmm 🤔 Looks like I don't have that table: ![image](https://user-images.githubusercontent.com/1553902/277942133-0db9b965-469e-4ca8-81fe-793b0168cadc.png)
> 
> I'm using Ferdium with a PostgreSQL database.

It should be the `adonis_schema` table (I think)
