### ISSUE TITLE
csrfField is not a function

### ISSUE THREAD

**Issue by RealSocius** [ferdium/ferdium-server#96]
So I am experiencing an error when visiting "/user/login".

{
  "message": "csrfField is not a function",
  "stack": "Error: csrfField is not a function\n    at anonymous (/app/build/resources/views/dashboard/login.edge:22:0)\n    at Template.reThrow (/app/node_modules/.pnpm/edge.js@5.5.1/node_modules/edge.js/build/src/Template/index.js:174:15)\n    at template (eval at wrapToFunction (/app/node_modules/.pnpm/edge.js@5.5.1/node_modules/edge.js/build/src/Template/index.js:60:20), <anonymous>:217:10)\n    at Template.renderCompiled (/app/node_modules/.pnpm/edge.js@5.5.1/node_modules/edge.js/build/src/Template/index.js:80:57)\n    at Template.render (/app/node_modules/.pnpm/edge.js@5.5.1/node_modules/edge.js/build/src/Template/index.js:135:21)\n    at EdgeRenderer.render (/app/node_modules/.pnpm/edge.js@5.5.1/node_modules/edge.js/build/src/Renderer/index.js:37:103)\n    at LoginController.show (/app/app/Controllers/Http/Dashboard/LoginController.ts:12:17)\n    at Injector.callAsync (/app/node_modules/.pnpm/@adonisjs+fold@8.2.0/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)",
  "code": "E_RUNTIME_EXCEPTION"
}

Can anyone maybe help me out. If you need more information just let me know :D

**Comment by RealSocius** [comment]
Duplicate: https://github.com/ferdium/ferdium-server/issues/86
